### ISSUE TITLE
functionality: specify performance claims

### ISSUE THREAD

**Issue by corybrunson** [mingzehuang/latentcor#10]
The software performs very much as advertised, with even greater improvements in performance on larger data sets that i've tried (generated using the helpful `gen_data()` function)! However, this performance improvement is not quantified in the documentation, so far as i've found. Presumably this is contained in the cited papers and perhaps also in the software paper. Because performance is the core motivation for the package, though, i think it important to also summarize quantified performance gains (whether theoretical or experimental) in the documentation, e.g. the README. (This would also allow me, as a reviewer, to evaluate the claims.)

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/3634)._

**Comment by muellsen** [comment]
We already started to add microbenchmarks/ timings to the vignette/README. In your view, would it be also beneficial to have a speed-up plot in the paper?

**Comment by corybrunson** [comment]
I think that would suffice! I'll have a look at the vignette again when they're included.

Since your claims involve memory as well as time, it would be good to include comments on both.

In addition to example runs, if there are more comprehensive results in the cited journal articles, then i think it would also be important to mention them.

**Comment by mingzehuang** [comment]
@corybrunson See the microbenchmark for both examples in README.md [here](https://mingzehuang.github.io/latentcor/index.html). Also microbenchmark in the code chunk in section `Approximation method (method = "approx")` in Vignette ['latentcor_math'](https://mingzehuang.github.io/latentcor/articles/latentcor_math.html).
Thank you very much!

**Comment by corybrunson** [comment]
Thank you! I'm sorry, i meant to come back to this days ago. I do think the examples suffice to illustrate the claim.

However, asking again to be sure: Do the cited papers report more systematic justifications for the claims, e.g. simulations over a range of scales or big-O proofs of runtime? If not, then i think it will be fine to stop here. If so, i think it would be good to mention these more rigorous results and cite the papers that report them. Does that make sense?

**Comment by corybrunson** [comment]
I took a look at the approximation paper (Yoon &al, 2021), and i see that it makes a thorough case for improved performance with little cost to accuracy. So for this issue i would be satisfied by a sentence in the README or the performance vignette (or both) explaining that this more comprehensive demonstration of the performance claims can be found in that paper.

**Comment by mingzehuang** [comment]
Thank you for your update @corybrunson ! In the math vignette "latentcor_math", we just added a section "Speed Comparison" under "Approximation method (method = "approx")" with performance claim and log-log plot for different dimensions.
Let us know if any more need to be added. Thanks!

**Comment by mingzehuang** [comment]
[latentcor_math](https://mingzehuang.github.io/latentcor/articles/latentcor_math.html)

**Comment by corybrunson** [comment]
@mingzehuang this looks good! I might have missed the references to the 2021 paper on a previous read, but together with the plot the vignette is now very clear about the performance claims.
