### ISSUE TITLE
documentation: statement of need

### ISSUE THREAD

**Issue by corybrunson** [mingzehuang/latentcor#11]
Similarly to #10, the software documentation should include a clear statement of need. This could be a single sentence summarizing motivations from the software paper, located in the DESCRIPTION, the README, and/or the manual page for `latentcor()`.

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/3634).

**Comment by mingzehuang** [comment]
Thank you for your suggestion, Dr.Brunson! We've added statement of need into README.md and Vignette. Also a sentence for statement of need in DESCRIPTION.
Let us know any more needed:)

**Comment by corybrunson** [comment]
@mingzehuang they do the job! To be clear, the requirement for the documentation is not the same as for the paper, so it would be fine if there were merely a sentence or two summary rather than a full section if that's what you'd prefer. But the issue is certainly resolved.

**Comment by mingzehuang** [comment]
Thank you so much! I'll make it shorter:)
