### ISSUE TITLE
split vignettte?

### ISSUE THREAD

**Issue by corybrunson** [mingzehuang/latentcor#12]
The vignette is an extremely helpful part of the installation, though it runs quite long and seems to naturally divide into halves: practical use and theoretical underpinnings. Would it make sense to split it into separate vignettes that users can read based on need? For example, based on the first few screens' worth, i wouldn't guess that the vignette also included mathematical formulations and would assume that i would have to consult the papers. (This is a question, not a request, and is not holding up my review!)

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/3634)._

**Comment by mingzehuang** [comment]
Thank you @corybrunson ! We've split the vignette into two parts: one called "latentcor", another called "latentcor_math". So that users can choose whatever they want to read.
Let us know if anything could be improved:)

**Comment by corybrunson** [comment]
Yes, i just noticed, thank you!
