### ISSUE TITLE
documentation: recognized input classes

### ISSUE THREAD

**Issue by corybrunson** [mingzehuang/latentcor#13]
This is a small point, but one that might cause confusion for users new to R. The documentation explains that the input `X` to `latentcor()` should be a numeric data matrix, but this could mean either an object of class 'matrix' or of class 'data.frame'. Both are understood by `latentcor()` though this is not always the case, so i would suggest making explicit that either data type can be passed, or that the input will be coerced to a numeric matrix using `data.matrix()`.

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/3634)._

**Comment by mingzehuang** [comment]
Thank you for your detailed review, @corybrunson ! The input data can be either matrix or data frame as long as it's numeric. We've modify documentation to declare it explicitly. It should be checked if it's numeric rather than simply coerced. We've modified the code for it! Thank you so much!

**Comment by corybrunson** [comment]
It looks great, thank you!
