### ISSUE TITLE
Feature request: make nearPD optional

### ISSUE THREAD

**Issue by zdk123** [mingzehuang/latentcor#15]
I have a small request to make using nearPD a user-defined option here (as for [use.nearPD in mixedCCA](https://github.com/irinagain/mixedCCA/blob/master/R/estimateR.R#L29)):
https://github.com/mingzehuang/latentcor/blob/master/R/latentcor.R#L119-L120

I'm adapting latentcor this for use in SpiecEasi so I actually don't need a PD correlation matrix here. I'd be happy to contribute the changes if you'd accept a PR.

**Comment by mingzehuang** [comment]
Thank you so much @zdk123 for using our package! Actually, there is an "Rpointwise" in output list which is the original latent correlation matrix before PD adjustment, whereas the "R" in output list is the latent correlation matrix after PD adjustment. I think you need the "Rpointwise":)
I think our documentation may be a bit misleading in terms of "Rpointwise". We will directly point out that it is original unadjusted latent correlation matrix. Thank you for your comment!

**Comment by zdk123** [comment]
Thanks @mingzehuang - Rpointwise is indeed what I want. From a performance standpoint though, I might still recommend splitting out the pointwise and the shrinkage/projection estimations into two functions. Since for large matrices I would wind up doing a expensive eigendecompositions that I don't actually need.

**Comment by zdk123** [comment]
Oh and a related performance point, running [`eigen` in latentcor.R#L117](https://github.com/mingzehuang/latentcor/blob/master/R/latentcor.R#L117) is actually redundant. `Matrix::nearPD` will run the exact same function internally during the first iteration and, if the matrix is positive definite, will return the input without further adjustment.

**Comment by mingzehuang** [comment]
Thank you so much, @zdk123 ! I think we're going to take your suggestion and add user-defined "use.nearPD" and delete the redundant code line ASAP:)

**Comment by mingzehuang** [comment]
Hi, @zdk123 . Thank you for your suggestions. We've updated the package according to your suggestions and latentcor (v1.2.0) on [CRAN](https://CRAN.R-project.org/package=latentcor) now!
Let us know if anything more we can do!

**Comment by zdk123** [comment]
cheers, thanks!
