### ISSUE TITLE
No Contributors guide or code of conduct

### ISSUE THREAD

**Issue by rmflight** [mingzehuang/latentcor#2]
Ideally, open source software should have a [guide for new contributors](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors), or a [code of conduct](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project).

**Comment by irinagain** [comment]
Thank you for catching. We have added contributions guide and code of conduct as separate .md files in the repo, with readme linking to those files.
