### ISSUE TITLE
why is the main function estR and not "latentcor"?

### ISSUE THREAD

**Issue by rmflight** [mingzehuang/latentcor#3]
The stated reason for the package is for estimating "latent" correlations, hence the package name of "latentcor", which seems great. But why is the main function not also named "latentcor"?? It seems odd to use "estR" as the main function. I realize it's because you are doing the "estimation" of "R^2", but underneath the entire logic is based on the "latentcor" method and framework.

**Comment by irinagain** [comment]
Great idea. We will change the name and update here once it is done

**Comment by mingzehuang** [comment]
We've changed the name of function to "latentcor". Thanks!
