### ISSUE TITLE
documentation of parameter values

### ISSUE THREAD

**Issue by rmflight** [mingzehuang/latentcor#5]
The vignette provides some information on what these various parameters do:

* nu
* tol
* ratio

And how changing them will change the results?? Even a second vignette for those specific parameters might be good to see.

**Comment by irinagain** [comment]
We have expanded the base documentation for all three parameters in function `latentcor` as well as added some short Details (with vignette having expanded version). The vignette already contained information on these parameters, but we expanded it and provided hyperlinks across sections to make it more clear where to find the information (see in particular a new overview right under Estimation Methods). The parameters are inherently connected to the mathematical approaches used for estimation, and thus we believe should be described in that framework to be meaningful. Many users will likely never need to change these parameters (hence the default recommended values), however we also came across users who wanted that flexibility for their specific applications. 

Extra point for `ratio` - we will add explicit timing results on this one to illustrate the computational effect (the accuracy effect can be seen in the vignette under Approximation method section). Both effects are also discussed in the referenced paper (Yoon et al., 2021), but we agree it's good to reiterate them with explicit examples here. As there is a separate issue on timing results, we will reflect those changes there.

Let us know if anything is still unclear.

**Comment by irinagain** [comment]
We have also separated the vignette into "getting started" and "mathematical framework", which hopefully makes it easier to get started with default parameters, as well as make it more clear where to look for how changing the default parameters may affect the performance

**Comment by rmflight** [comment]
Great!
